version: '2.1'

services:

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - users-service
      - web-service

  users-db:
    container_name: users-db
    # build: https://github.com/rahmonov/flask-microservice-users.git#master:project/db
    build:
      context: ../flask-microservices-users/project/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
    healthcheck:
      test: exit 0


  users-service:
    container_name: users-service
    # build: https://github.com/rahmonov/flask-microservice-users.git
    build:
      context: ../flask-microservices-users
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build:
      # context: https://github.com/rahmonov/flask-microservice-client.git
      context: ../flask-microservices-client
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service
